/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Interface;
import com.Client;
import com.Servidor;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Marco
 * la modularidad se da en la creacion de paquetes que se alojan dentro de distintos módulos
 */
public class ChatServer extends javax.swing.JFrame implements Observer {// aqui se evidencia la herencia de la clase swing

    /**
     * Creates new form ChatWin
     */
    public ChatServer() {
        initComponents();
        this.getRootPane().setDefaultButton(this.BtnSend);
        
        Servidor LocalServer = new Servidor(6000);// Aqui se evidencia la instanciación
        LocalServer.addObserver(this);
        Thread Flow1 = new Thread(LocalServer);
        Flow1.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CanvaChat = new javax.swing.JPanel();
        TxtMenssage = new javax.swing.JTextField();
        BtnSend = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtChat = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CanvaChat.setBackground(new java.awt.Color(204, 102, 255));
        CanvaChat.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos I 2020 Server", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 153))); // NOI18N

        TxtMenssage.setBackground(new java.awt.Color(255, 255, 153));
        TxtMenssage.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        TxtMenssage.setForeground(new java.awt.Color(204, 102, 255));
        TxtMenssage.setText("Type your menssage...");

        BtnSend.setBackground(new java.awt.Color(255, 0, 255));
        BtnSend.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        BtnSend.setForeground(new java.awt.Color(255, 255, 153));
        BtnSend.setText("SEND");
        BtnSend.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 102), new java.awt.Color(255, 255, 102), new java.awt.Color(255, 255, 102), new java.awt.Color(255, 255, 102)));
        BtnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSendActionPerformed(evt);
            }
        });

        TxtChat.setBackground(new java.awt.Color(255, 255, 153));
        TxtChat.setColumns(20);
        TxtChat.setRows(5);
        jScrollPane1.setViewportView(TxtChat);

        javax.swing.GroupLayout CanvaChatLayout = new javax.swing.GroupLayout(CanvaChat);
        CanvaChat.setLayout(CanvaChatLayout);
        CanvaChatLayout.setHorizontalGroup(
            CanvaChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CanvaChatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CanvaChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(CanvaChatLayout.createSequentialGroup()
                        .addComponent(TxtMenssage, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        CanvaChatLayout.setVerticalGroup(
            CanvaChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CanvaChatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CanvaChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtMenssage)
                    .addComponent(BtnSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CanvaChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CanvaChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSendActionPerformed
        
        String message = "Server: " + this.TxtMenssage.getText() + "\n";
        this.TxtChat.append(message);
        
        Client LocalClient = new Client(5000, message);
        
        Thread Flow2 = new Thread(LocalClient);
        Flow2.start();
        
    }//GEN-LAST:event_BtnSendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatServer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSend;
    private javax.swing.JPanel CanvaChat;
    private javax.swing.JTextArea TxtChat;
    private javax.swing.JTextField TxtMenssage;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        
        this.TxtChat.append((String) arg);
        
    }
}
